# Generated by Django 4.1 on 2022-08-04 09:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(blank=True, max_length=150, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_point', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=150)),
                ('date_awarded', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.account')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_instrument', models.CharField(blank=True, choices=[('metric', 'Metric'), ('imperial', 'Imperial'), ('custom', 'Custom')], max_length=30, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reward_point', models.PositiveIntegerField(default=1)),
                ('awarded', models.BooleanField(default=False)),
                ('date_awarded', models.DateTimeField(auto_now_add=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.account')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='device')),
                ('reward_point', models.PositiveIntegerField(default=5)),
                ('awarded', models.BooleanField(default=False)),
                ('date_awarded', models.DateTimeField(blank=True, null=True)),
                ('battery_life', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('connection_status', models.CharField(choices=[('success', 'Connected'), ('danger', 'Not Connected')], default='danger', max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.account')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=100, null=True)),
                ('app_name', models.CharField(choices=[('google', 'Google Fit'), ('samsung', 'Samsung Health'), ('apple', 'Apple Health'), ('garmin', 'Garmin Connect'), ('xiaomi', 'Xiaomi Mi Fit')], max_length=200)),
                ('thumbnail', models.ImageField(upload_to='app')),
                ('reward_point', models.PositiveIntegerField(default=5)),
                ('awarded', models.BooleanField(default=False)),
                ('date_awarded', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('success', 'Connected'), ('danger', 'Not Connected')], default='danger', max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.account')),
            ],
        ),
    ]
